version: "3.9"

services:
  web:
    build: .
    image: branya/hotel_web:1.0.0
    container_name: web
    volumes:
      - static_volume:/opt/src/static
      - media_volume:/opt/src/media
    command: >
      bash -c " 
      python manage.py makemigrations;
      python manage.py migrate;
      python manage.py createsuperuser --no-input;
      python manage.py collectstatic --no-input;
      gunicorn core.wsgi:application --workers "${GUNICORN_WORKERS:-2}" --bind 0.0.0.0:8000 "
    env_file:
      - ./.env
    healthcheck:
      test: curl --fail -s http://localhost:8000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    build: ./postgres
    image: branya/hotel_db:1.0.0
    env_file:
      - ./.env
    volumes:
      - db_volume:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "/usr/src/healthcheck.sh"]
      interval: 30s
      timeout: 2s
      retries: 5
    restart: always

  nginx:
    build: ./nginx
    image: branya/hotel_nginx:1.0.0
    env_file:
      - ./.env
    volumes:
      - static_volume:/opt/src/static
      - media_volume:/opt/src/media
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/usr/src/healthcheck.sh"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always


volumes:
  db_volume:
    name: hotel_web
  media_volume:
    name: hotel_media
  static_volume:
    name: hotel_static
